- name: Create development directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "~/.nvm"
    - "$HOME/Development"
    - "$HOME/Development/Personal"
    - "$HOME/Development/Scratch"
    - "$HOME/Development/Obsidian/Dev/.obsidian/plugins"
