- name: Set Mac's Terminal profile to Pro by default
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string Pro
    - defaults write com.apple.terminal 'Startup Window Settings' -string Pro
