## Zsh
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

ZSH_THEME="robbyrussell"
DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="false"

## General config
skip_global_compinit=1

##
## Oh my ZSH Plugins
###
plugins=(
  ansible
  command-not-found
  docker
  fzf-tab
  gcloud
  git
  httpie
  kubectl
  pip
  pyenv
  python
  sudo
  vagrant
  vi-mode
  z
  zsh-autosuggestions
  zsh-completions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
setopt inc_append_history
setopt share_history

# Aliases

## Shortcuts
alias dev="cd $HOME/Development"
alias obsidian="cd $HOME/Development/Obsidian/Dev/.obsidian/plugins"
alias docs="cd $HOME/Documents"
alias atlassian="cd $HOME/Development/Atlassian"

## Commands
alias ll="ls -la"

# NVM configuration 
export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
