## Zsh
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

ZSH_THEME="robbyrussell"
DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="false"

## General config
skip_global_compinit=1

##
## Oh my ZSH Plugins
###
plugins=(
  ansible
  command-not-found
  docker
  fzf-tab
  gcloud
  git
  httpie
  kubectl
  pip
  pyenv
  python
  sudo
  vagrant
  vi-mode
  z
  zsh-autosuggestions
  zsh-completions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
setopt inc_append_history
setopt share_history

# Aliases

## Shortcuts
alias dev="cd $HOME/Development"
alias obsidian="cd $HOME/Development/Obsidian/Dev/.obsidian/plugins"

## Commands
alias ll="ls -la"
