---
- name: Create development directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "~/.nvm"
    - "$HOME/Development"
    - "$HOME/Development/Personal"
    - "$HOME/Development/Atlassian"
    - "$HOME/Development/Scratch"
    - "$HOME/Development/Obsidian/Dev/.obsidian/plugins"
