---
- name: Install git package
  community.general.homebrew:
    name: git
    state: latest

- name: Create git config
  ansible.builtin.copy:
    src: git/gitconfig
    dest: ~/.gitconfig
    mode: 0644
