---
- name: Terminal
  import_tasks: terminal.yml

- name: Folders
  import_tasks: folders.yml

- name: Node
  import_tasks: node.yml

- name: Obsidian
  import_tasks: obsidian.yml

- name: Zsh
  import_tasks: zsh.yml

- name: Git
  import_tasks: git.yml

- name: Command Line Tools
  import_tasks: cli.yml
