- name: Install Apps
  community.general.homebrew_cask:
    name: "{{ item }}"
  ignore_errors: yes
  loop:
    - google-chrome
    - slack
    - visual-studio-code
    - obsidian
    - raycast
    - thingsmacsandboxhelper
    - bitwarden
